#!/usr/bin/env ruby
# This scripts adds all changes and commits with a 'wip' message
# For safety this script refuses to run on master
require 'optparse'

def shell(command)
  output = `#{command}`

  exit(-1) unless $?.success?

  output
end

branch=shell("git rev-parse --abbrev-ref HEAD")

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: git work [options]"

  opts.on("-f", "--force", "Force script execution on master") do |f|
    options[:force] = f
  end

  opts.on("-p", "--push", "Push after commit") do |p|
    options[:push] = p
  end

  opts.on("-m M", "--message M", String, "Commit message") do |m|
    options[:message] = m
  end
end.parse!

if branch == "master" && !options[:force]
  puts "Can't run this on the master branch"
  exit(-1)
end

puts shell("git add --all")
puts shell("git commit -m '#{options[:message] || 'wip'}'")
puts shell("git push -u origin #{branch}") if options[:push]
