#!/usr/bin/env ruby

def shell(command)
  output = `#{command}`

  exit(-1) unless $?.success?

  output
end

base = shell("git merge-base HEAD #{ARGV[0]}")

puts shell("git reset --soft #{base}")

puts "Ready to commit!"

